# Generated by Django 3.2.14 on 2022-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10),
        ),
    ]
