# Generated by Django 3.2 on 2022-09-26 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email_address', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date(2022, 9, 26))),
                ('installation_type', models.CharField(choices=[('Club', 'Club'), ('Corporate', 'Corporate'), ('Hotel', 'Hotel')], default='Club', max_length=40)),
            ],
        ),
    ]
