# Generated by Django 3.2.14 on 2022-10-04 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
    ]
