# Generated by Django 3.2.14 on 2022-12-01 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0009_alter_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
    ]
